/*
 * Auto-generated by tools/generate_io_config.py from:
 * io_processor.yaml
 * DO NOT EDIT MANUALLY - Markdown/YAML Drives the Code (SSOT)
 */

#ifndef ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP
#define ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP

#include "abstractx/hal/io_processor.hpp"

namespace abstractx::target::generated {

inline constexpr hal::AutoChannelConfig TARGET_AUTO_CHANNELS[2] = {
    {
        .channel_id = 0,
        .auto_mode = true,
        .trigger_mode = hal::TriggerMode::GpioEdge,
        .trigger_pin = 20,
        .trigger_rising = true,
        .timer_period_us = 0,
        .bus_type = hal::BusType::Spi,
        .bus_index = 0,
        .bus_speed_hz = 10000000,
        .cs_pin = 0,
        .tx_cmd = {0x9D},
        .tx_len = 1,
        .rx_len = 15,
        .tlp_channel = 2,
        .tlp_tag = 1
    },
    {
        .channel_id = 1,
        .auto_mode = true,
        .trigger_mode = hal::TriggerMode::Timer,
        .trigger_pin = 0,
        .trigger_rising = true,
        .timer_period_us = 20000,
        .bus_type = hal::BusType::I2c,
        .bus_index = 1,
        .bus_speed_hz = 400000,
        .cs_pin = 0,
        .tx_cmd = {0x00},
        .tx_len = 1,
        .rx_len = 6,
        .tlp_channel = 2,
        .tlp_tag = 3
    }
};

inline constexpr size_t NUM_TARGET_AUTO_CHANNELS = 2;

} // namespace abstractx::target::generated

#endif // ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP
