#!/usr/bin/env python3
"""
Copyright (C) 2026 Tim Michals
SPDX-License-Identifier: GPL-3.0-or-later

AbstractX Target I/O Processor Configuration Generator (generate_io_config.py)
------------------------------------------------------------------------------
Reads targets/<target>/io_processor.yaml and generates a static, zero-heap
constexpr C++ header containing AutoChannelConfig arrays and setup descriptors.

Usage:
  python3 tools/generate_io_config.py targets/pico2w_rp2350/io_processor.yaml [output.hpp]
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Run: pip install pyyaml")
    sys.exit(1)

CPP_TEMPLATE = """/*
 * Auto-generated by tools/generate_io_config.py from:
 * {yaml_file}
 * DO NOT EDIT MANUALLY - Markdown/YAML Drives the Code (SSOT)
 */

#ifndef ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP
#define ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP

#include "abstractx/hal/io_processor.hpp"

namespace abstractx::target::generated {{

inline constexpr hal::AutoChannelConfig TARGET_AUTO_CHANNELS[{num_channels}] = {{
{channel_entries}
}};

inline constexpr size_t NUM_TARGET_AUTO_CHANNELS = {num_channels};

}} // namespace abstractx::target::generated

#endif // ABSTRACTX_TARGET_GENERATED_IO_CONFIG_HPP
"""

ENTRY_TEMPLATE = """    {{
        .channel_id = {ch_id},
        .auto_mode = {auto_mode},
        .trigger_mode = hal::TriggerMode::{trigger_mode},
        .trigger_pin = {trigger_pin},
        .trigger_rising = {trigger_rising},
        .timer_period_us = {timer_period_us},
        .bus_type = hal::BusType::{bus_type},
        .bus_index = {bus_index},
        .bus_speed_hz = {bus_speed_hz},
        .cs_pin = {cs_pin},
        .tx_cmd = {{{tx_cmd_bytes}}},
        .tx_len = {tx_len},
        .rx_len = {rx_len},
        .tlp_channel = {tlp_channel},
        .tlp_tag = {tlp_tag}
    }}"""

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 tools/generate_io_config.py <path_to_io_processor.yaml> [output.hpp]")
        sys.exit(1)

    yaml_path = Path(sys.argv[1])
    if not yaml_path.exists():
        print(f"Error: File not found: {yaml_path}")
        sys.exit(1)

    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else yaml_path.parent / "include" / "generated_io_config.hpp"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    io_proc = data.get("io_processor", {})
    channels = io_proc.get("channels", [])

    entries = []
    for ch in channels:
        ch_id = ch.get("id", 0)
        auto_mode = "true" if ch.get("auto_mode", True) else "false"
        
        trig = ch.get("trigger", {})
        trig_mode_str = trig.get("mode", "gpio_edge").lower()
        if trig_mode_str == "gpio_edge":
            trig_mode = "GpioEdge"
        elif trig_mode_str == "timer":
            trig_mode = "Timer"
        else:
            trig_mode = "None"
            
        trigger_pin = trig.get("pin", 0)
        trigger_rising = "true" if trig.get("edge", "rising") == "rising" else "false"
        timer_period_us = trig.get("period_us", 0)

        bus = ch.get("bus", {})
        bus_type_str = bus.get("type", "spi").lower()
        if bus_type_str == "spi":
            bus_type = "Spi"
        elif bus_type_str == "i2c":
            bus_type = "I2c"
        elif bus_type_str == "uart":
            bus_type = "Uart"
        else:
            bus_type = "Spi"

        bus_index = bus.get("index", 0)
        bus_speed_hz = bus.get("speed_hz", 10000000)
        cs_pin = bus.get("cs_pin", 0)

        xfer = ch.get("transfer", {})
        tx_cmd_raw = xfer.get("tx_cmd", [0])
        tx_cmd_bytes = ", ".join([f"0x{b:02X}" for b in tx_cmd_raw])
        tx_len = xfer.get("tx_len", len(tx_cmd_raw))
        rx_len = xfer.get("rx_len", 15)

        tlp = ch.get("tlp_output", {})
        tlp_channel = tlp.get("channel", 2)
        tlp_tag = tlp.get("tag", 1)

        entry = ENTRY_TEMPLATE.format(
            ch_id=ch_id,
            auto_mode=auto_mode,
            trigger_mode=trig_mode,
            trigger_pin=trigger_pin,
            trigger_rising=trigger_rising,
            timer_period_us=timer_period_us,
            bus_type=bus_type,
            bus_index=bus_index,
            bus_speed_hz=bus_speed_hz,
            cs_pin=cs_pin,
            tx_cmd_bytes=tx_cmd_bytes,
            tx_len=tx_len,
            rx_len=rx_len,
            tlp_channel=tlp_channel,
            tlp_tag=tlp_tag
        )
        entries.append(entry)

    formatted_entries = ",\n".join(entries)
    cpp_content = CPP_TEMPLATE.format(
        yaml_file=yaml_path.name,
        num_channels=len(channels),
        channel_entries=formatted_entries
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(cpp_content)

    print(f"[SUCCESS] Generated C++ I/O Config header: {out_path} ({len(channels)} channels)")

if __name__ == "__main__":
    main()
